# Generated by Django 4.0.6 on 2022-07-30 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=250)),
                ('detail1', models.CharField(max_length=250)),
                ('detail2', models.CharField(max_length=250)),
                ('detail4', models.CharField(max_length=250)),
                ('detail3', models.CharField(max_length=250)),
                ('detail5', models.CharField(max_length=250)),
            ],
        ),
    ]
